version: 0.2
phases:
  install:
    commands:
      - sudo yum update -y
      - sudo yum install -y httpd php php-mysqlnd mysql git
  build:
    commands:
      - sudo systemctl start httpd
  post_build:
    commands:
      - echo "Deployment successful!"
artifacts:
  files:
    - '**/*'
